name: OneBlockCore
version: '${project.version}'
main: net.cubeslide.oneblock.oneblockcore.OneBlockCore
api-version: 1.19
authors: [ Lara, Luca ]
commands:
  spawn:
  vanish:
    permission: OneBlockCore.vanish
  tpa:
  tpaccept:
    aliases: tpyes
  tpdeny:
    aliases: tpno
  visit:
    permission: OneBlockCore.visit.others
